server:
  port: 8080

spring:
  application:
    name: healthcare

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # change to 'validate' in production
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql

twilio:
  account-sid: ${TWILIO_ACCOUNT_SID}
  auth-token: ${TWILIO_AUTH_TOKEN}
  from-number: ${TWILIO_FROM_NUMBER}

ai:
  hf:
    api-key: ${HF_API_KEY}
    chat-model: meta-llama/Llama-3.1-8B-Instruct
    chat-url: https://router.huggingface.co/v1/chat/completions
    temperature: 0
